Repository pnuniverse/plato-calendar-2, pull requests merged in 2024-03, with the labels that each got.

#4 Calendar front 달력 설계
  .eslintrc.json
  assets/calendar.html
  assets/img/down.png
  assets/img/homework.png
  assets/img/left.png
  assets/img/loading.png
  assets/img/quiz.png
  assets/img/right.png
  assets/img/up.png
  assets/img/video.png
  assets/img/zoom.png
  assets/new-style.css
  assets/prev-style.css
  assets/style.css
  manifest.json
  scripts/content-script.js
Labels: Feature

#3 Feature/과제 정보 크롤링
  scripts/content-script.js
  scripts/getInfo.js
  service-worker.js
Labels: Feature

#5 Data Fetch 풀리퀘
  assets/calendar.html
  assets/prev-style.css
  manifest.json
  scripts/content-script.js
  scripts/getInfo.js
Labels: Feature

#9 feat: courseId, courseName 추가
  scripts/content-script.js
  scripts/getInfo.js
Labels: Feature

#11 fix: 캘린더 셀 초기화
  scripts/content-script.js
Labels: Fix

#10 Fix/병렬화 #7
  assets/loader.css
  manifest.json
  scripts/content-script.js
  scripts/loading.js
Labels: Fix, Feature

#12 Feature/모달 디자인
  scripts/content-script.js
  scripts/getInfo.js
Labels: Feature

#14 feat: 설치 및 업데이트 시 공지
  assets/noti.html
  service-worker.js
Labels: Feature

#17 Feature/완료된 과제 처리 #16
  assets/prev-style.css
  scripts/content-script.js
Labels: Feature

#18 feat: 수동 동기화
  assets/calendar.html
  assets/prev-style.css
  scripts/content-script.js
Labels: Feature

#19 Fix/과제 영어
  scripts/content-script.js
  scripts/getInfo.js
Labels: Fix

#21 Feature/동기화 가능 시간 표시 #20
  scripts/content-script.js
  scripts/getInfo.js
Labels: Feature

#23 완료 되지 않는 과제 수만큼 달력 표시
  scripts/content-script.js
Labels: Feature

#25 fix: 매칭된 과제 정보 제거
  scripts/content-script.js
  scripts/getInfo.js
Labels: Fix

#32 devlog: promise 중첩해서 쓰기
  Devlog/0x03 promise 중첩해서 쓰기.md
Labels: Devlog

#38 feat: 과제 개수 렌더링 방식 변경
  scripts/content-script.js
Labels: Feature

#37 feat: 과제 마감 일자 및 시각 변경
  scripts/getInfo.js
Labels: Feature

#40 feat: 과제 표기 방식 변경
  scripts/content-script.js
Labels: Feature
